### ISSUE TITLE
Pressing "next" rapidly breaks the slider

### ISSUE THREAD

**Issue by hirbod** [Richi2293/rn-falcon-app-intro#10]
Looks like the index get messed up when I hit "next" button very quickly, until the animation to the next slide has finished. It's end up in a unfinishable state.

**Comment by hirbod** [comment]
This should be an easy fix. It looks like "isScrolling" is never set, therefore, this line is pretty useless currently.

https://github.com/Richi2293/rn-falcon-app-intro/blob/master/AppIntro.js#L145

**Comment by Richi2293** [comment]
It seemed a good fix, made the merge and updated to version 1.2.1
