### ISSUE TITLE
Advanced Example usage doesn't work.

### ISSUE THREAD

**Issue by nicoache1** [Richi2293/rn-falcon-app-intro#21]
### Description.
Using the example and running in ios, when you try to swipe it break with the next red screen.
<img width="397" alt="Screen Shot 2019-11-10 at 6 32 26 PM" src="https://user-images.githubusercontent.com/26419582/68551162-b6a84b00-03e8-11ea-967b-ea204efc3f9e.png">

### System Info
System:
    OS: macOS 10.14.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 1.74 GB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.11.4 - ~/.nvm/versions/node/v8.11.4/bin/node
    Yarn: 1.13.0 - ~/.yvm/versions/v1.13.0/bin/yarn
    npm: 6.7.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28
      Build Tools: 28.0.3
      System Images: android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6
    react-native: 0.60.3 => 0.60.3
  npmGlobalPackages:
    react-native-cli: 2.0.1

**Comment by Richi2293** [comment]
Hi,

I made an update, please try again with version 1.2.5.
I did tests, and for me the Example project works correctly on both Android and iOS.
Let me know, thanks
