### ISSUE TITLE
rn-falcon-app-intro: Appears to be a git repo or submodule

### ISSUE THREAD

**Issue by johnlim5847** [Richi2293/rn-falcon-app-intro#24]
First of all awesome work! it works like a charm just that the npm package contains git related file which makes any npm command fail after installing `rn-falcon-app-intro`.

```
npm ERR! path /Users/aaaa/Desktop/aaaaa/node_modules/rn-falcon-app-intro
npm ERR! code EISGIT
npm ERR! git /Users/aaaa/Desktop/aaaaa/node_modules/rn-falcon-app-intro: Appears to be a git repo or submodule.
npm ERR! git     /Users/aaaa/Desktop/aaaaa/node_modules/rn-falcon-app-intro
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/aaaa/.npm/_logs/2019-12-04T13_08_39_940Z-debug.log
```
After I manually remove `.git` and `.github` in `node_modules/rn-falcon-app-intro` the npm command work as expected

If you can remove it in your package for the upcoming release will be great! 

Once again thanks for this awesome package!!

**Comment by Richi2293** [comment]
Hi,

thanks!

Completed the change, version 1.2.7
