### ISSUE TITLE
onSlideChange index value is super buggy with >= 3 slides

### ISSUE THREAD

**Issue by andrekovac** [Richi2293/rn-falcon-app-intro#27]
When there are at least three slides, the `index` value of the prop `onSlideChange` goes crazy when sliding your finger horizontally. When at the middle slide, if you just tap and move it sligtly to the right or left, it will suddenly trigger `onSlideChange` and change the index again, although the slide didn't really change.

Here's what I'm referring to:

```js
<AppIntro
  onSlideChange={index => {
    console.log({ index });  // index will be wrong most of the time.
  }}
>
...
```

**Comment by Richi2293** [comment]
Hi, 

thanks for the issue.

I think I solved it in version 1.2.8 updated a few minutes ago.
Let me know if it's fixed, thanks
