### ISSUE TITLE
Programmatically navigate to next slide

### ISSUE THREAD

**Issue by venix** [Richi2293/rn-falcon-app-intro#29]
Is there a way to programmatically navigate to the next slide? I couldn't find from the docs anywhere.

Scenario: 
Using this slider as an intro to an app where the user needs to take some actions. I want to move on to the next slide once those actions are done. i.e Imagine a slide with two language options, once they press one of the two, it should move on to the next slide.

**Comment by Richi2293** [comment]
HI,

should be this function: "onNextBtnClick"

**Comment by Richi2293** [comment]
Hi,

@venix Now you can see a new example of what you meant (look at the file "Example/App1.js")

Sorry for the delay

**Comment by venix** [comment]
> Hi,
> 
> @venix Now you can see a new example of what you meant (look at the file "Example/App1.js")
> 
> Sorry for the delay

Thanks @Richi2293
