### ISSUE TITLE
Wrong center align for viewDots

### ISSUE THREAD

**Issue by yankovich** [Richi2293/rn-falcon-app-intro#4]
Hi, I find minor UI bug
<img width="499" alt="2019-03-08 14 17 36" src="https://user-images.githubusercontent.com/43784752/54025933-28226080-41ad-11e9-8873-5c467b2b7836.png">

When change flex: 0,5 to 1

`<AppIntro customStyles={{ viewDots: { flex: 1 }}} >`

The AppIntro component will be centered:

<img width="499" alt="2019-03-08 14 20 36" src="https://user-images.githubusercontent.com/43784752/54026106-c6162b00-41ad-11e9-9eee-85d706945a32.png">

**Comment by Richi2293** [comment]
Hi, 
thanks for the report!

I just checked and in fact I also noticed this problem on both iOS and Android.
Do you want to make a pull request?

**Comment by Richi2293** [comment]
Fixed on version 1.1.9
