### ISSUE TITLE
Prevent "Go to next Page" till condition is fulfilled? 

### ISSUE THREAD

**Issue by JaWoGit** [Richi2293/rn-falcon-app-intro#8]
Hi,

is there any way to prevent swiping to next page, till some condition (e.g. list size > 0) is fulfilled? 

Any help would be appreciated! Thanks!

**Comment by Richi2293** [comment]
I think you can manage it in your mobile app directly, through these props:

- onNextBtnClick -> check the condition if is fulfilled
- scrollEnabled  -> in this case maybe better to disable the scroll

**Comment by Richi2293** [comment]
I close the issue, in case there are problems open again
